--
-- PostgreSQL database dump
--

\restrict ajV70JcToAWXoXlG1cN4i98VoZPuraLhtElXDvaKEt2T3HLMvgpVW0qKB771gHs

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: PlainUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PlainUsers" (
    "Id" integer NOT NULL,
    "Username" text NOT NULL,
    "Password" text NOT NULL
);


ALTER TABLE public."PlainUsers" OWNER TO postgres;

--
-- Name: PlainUsers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PlainUsers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PlainUsers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Todos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Todos" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Completed" boolean NOT NULL
);


ALTER TABLE public."Todos" OWNER TO postgres;

--
-- Name: Todos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Todos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Todos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Username" text NOT NULL,
    "HashedPassword" text NOT NULL,
    "Role" text NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: PlainUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PlainUsers" ("Id", "Username", "Password") FROM stdin;
1	admin	admin
2	bob	secret
3	DD	admin
4	Dd	123
5	Dd_plain	123
\.


--
-- Data for Name: Todos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Todos" ("Id", "Title", "Description", "Completed") FROM stdin;
2	TEST_2	TEST_2	t
3	test_3	test_3	t
4	TEST_4	TEST_4	t
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Username", "HashedPassword", "Role") FROM stdin;
1	dd	$2a$11$Il10xmJaBvcBedfvYIZ7M./jyeZhtK.zELGmTohLPtITr9.FiMCM2	guest
2	d	$2a$11$DmHBf/iJAhlvavxwKzNSxubqgcSTGrxtQJOwcXukJ/mUyja9hytRS	guest
3	di	$2a$11$XP8Xv2NNPkOYDhoTelkrs.hETAjoaTDhO/JIrNbMO3QdYQHg2YaBy	user
4	Dd	$2a$11$XR8Pp2belQpxHb3h3DLVOO2wYREfr.PVn5iiH2IE/WQOhNDPSISUW	guest
5	admin	$2a$11$qZZf06IufzaDGkMoNMebFujfSXrBdrGh781WS.KtRHPVUf2xG0gB6	admin
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260412112021_InitialCreate	10.0.5
20260419064104_AddPlainUsers	10.0.5
\.


--
-- Name: PlainUsers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PlainUsers_Id_seq"', 5, true);


--
-- Name: Todos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Todos_Id_seq"', 4, true);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 5, true);


--
-- Name: PlainUsers PK_PlainUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PlainUsers"
    ADD CONSTRAINT "PK_PlainUsers" PRIMARY KEY ("Id");


--
-- Name: Todos PK_Todos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Todos"
    ADD CONSTRAINT "PK_Todos" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Users_Username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Username" ON public."Users" USING btree ("Username");


--
-- PostgreSQL database dump complete
--

\unrestrict ajV70JcToAWXoXlG1cN4i98VoZPuraLhtElXDvaKEt2T3HLMvgpVW0qKB771gHs

